apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bavarians-ingress
  namespace: bavarians-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - bavarians.waw.pl
        - www.bavarians.waw.pl
      secretName: bavarians-tls-cert
  rules:
    - host: bavarians.waw.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bavarians-service
                port:
                  number: 80
    - host: www.bavarians.waw.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bavarians-service
                port:
                  number: 80
