apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bavarians-ingress
  namespace: bavarians-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - bavarians.waw.pl
    - www.bavarians.waw.pl
    secretName: bavarians-tls
  rules:
  - host: bavarians.waw.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bavarians-service
            port:
              number: 8080
  - host: www.bavarians.waw.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bavarians-service
            port:
              number: 8080
