apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bavarians-ingress
  namespace: bavarians-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: bavarians.waw.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bavarians-service
            port:
              number: 8080
  - host: www.bavarians.waw.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bavarians-service
            port:
              number: 8080
