apiVersion: v1
kind: Service
metadata:
  name: bavarians-service
  namespace: bavarians-prod
  labels:
    app: bavarians
spec:
  type: NodePort
  selector:
    app: bavarians
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
